server:
  port: 80
spring:
  application:
    name: redis-sentinel
  redis:
    database: 10
    jedis:
      pool:
        max-active: 30
        max-idle: 8
        min-idle: 1
        max-wait: -1
    sentinel:
      master: mymaster
      nodes:
      - 192.168.124.13:26379
      - 192.168.124.13:29000
      - 192.168.124.13:29001
      - 192.168.124.13:29002

