#server:
#  port: 8080
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8080
eureka:
  client:
    service-url:
      # 配置其他Eureka服务的地址，而不是自己，比如10087 形成服务中心相互注册
      defaultZone: http://localhost:8080/eureka/
  server:
    enable-self-preservation: false # 开发下关闭自我保护模式（缺省为打开true） 当一个服务未按时进行心跳续约时 Eureka就会把当前实例的注册信息保护起来，不予剔除
    eviction-interval-timer-in-ms: 10 #失效的服务剔除出服务列表，单位是毫秒，生产环境不要修改。
spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中显示
