
spring:
  profiles:
    active: single

---
spring:
  profiles: single
  application:
    name: redis-demo
  redis:
    host: 192.168.124.13
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 1
        max-wait: -1

  customize:
    redisLockExpired: 10000

---
spring:
  profiles: multi
  application:
    name: redis-demo
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 1000
        max-idle: 8
        min-idle: 1
        max-wait: -1
customize:
  redisLockExpired: 10000
