server:
  port: 82
spring:
  application:
    name: ribbon-consumer # 应用名称，会在Eureka中显示
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/
# 修改负载均衡规则的配置入口 式是：{服务名称}.ribbon.NFLoadBalancerRuleClassName，值就是IRule的实现类。
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
